services:
  wserver:
    container_name: pixelated_wserver
    build:
      context: ../../
      dockerfile: apps/wserver/Dockerfile
    ports:
      - "${PORT}:5002"
    networks:
      - pixelated_network
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
      - ENV=${ENV}
    depends_on:
      - redis

  redis:
    container_name: pixelated_redis
    image: bitnami/redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - pixelated_network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - pixelated_wserver_redis_data:/bitnami/redis/data

networks:
  pixelated_network:
    driver: bridge

volumes:
  pixelated_wserver_redis_data:
